# Generated by Django 6.0.6 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('#fff740', 'Amarillo'), ('#ff7eb9', 'Rosa'), ('#7afcff', 'Azul'), ('#98ff98', 'Verde')], default='#fff740', max_length=7)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
