# Generated by Django 6.0.6 on 2026-07-17 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_postit_asignado_a_default_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='asignado_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postits', to=settings.AUTH_USER_MODEL),
        ),
    ]
